#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://43.201.124.70:3306/sys?serverTimezone=UTC&characterEncoding=UTF-8
#spring.datasource.username=4ilet
#spring.datasource.password=Fourilet@2023

spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://43.201.124.70:3306/Fourilet?serverTimezone=UTC&characterEncoding=UTF-8
      username: 4ilet
      password: Fourilet@2023
    # JPA Setting Info
    jpa:
      database: mysql
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate:
        ddl-auto: update # option type : create, create-drop, update, validate, none
      properties:
        hibernate:
          show_sql: true # ??????? ??? ?? sql ?? ??? ??.
          format_sql: true # sql ?? ??? ?? ??
          use_sql_comments: true # ??? ?? ??
logging:
  level:
    org:
      hibernate: info